default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: snow_meet_rails_development

test:
  <<: *default
  database: snow_meet_rails_test

production:
  <<: *default
  database: snow_meet_rails_production
  username: snow_meet_rails
  password: <%= ENV['SNOW_MEET_RAILS_DATABASE_PASSWORD'] %>