# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 150608f0f7c6c6e6337817e69b3c618c905b26851d0e01155bac552296f9724a8078a3746c65f9fde7ed58c6bb6be84695997368028eb7e25b05951acad17257

test:
  secret_key_base: a2d099dc9c2615dca98bd976378b20071b50e12ab2b24b2cb9ae9433f26ef3a4472bc5e3f8176cd770a8238d29cb1e2b3074741719df22f5dd8895b7f81536b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
